# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib sedonadb, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if (is.null(e)) {
    return(NULL)
  }

  if (inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_sedonadb__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_sedonadb__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}


`apply_crses_to_sf_stream` <- function(
  `stream_in_xptr`,
  `geometry_column_names`,
  `geometry_column_crses`,
  `stream_out_xptr`
) {
  invisible(.Call(
    savvy_apply_crses_to_sf_stream__impl,
    `stream_in_xptr`,
    `geometry_column_names`,
    `geometry_column_crses`,
    `stream_out_xptr`
  ))
}


`configure_proj_shared` <- function(
  `shared_library_path` = NULL,
  `database_path` = NULL,
  `search_path` = NULL
) {
  invisible(.Call(
    savvy_configure_proj_shared__impl,
    `shared_library_path`,
    `database_path`,
    `search_path`
  ))
}


`init_r_runtime_interrupts` <- function(`interrupts_call`, `pkg_env`) {
  invisible(.Call(savvy_init_r_runtime_interrupts__impl, `interrupts_call`, `pkg_env`))
}


`sedonadb_adbc_init_func` <- function() {
  .Call(savvy_sedonadb_adbc_init_func__impl)
}

### wrapper functions for InternalContext

`InternalContext_data_frame_from_array_stream` <- function(self) {
  function(`stream_xptr`, `collect_now`) {
    .savvy_wrap_InternalDataFrame(.Call(
      savvy_InternalContext_data_frame_from_array_stream__impl,
      `self`,
      `stream_xptr`,
      `collect_now`
    ))
  }
}

`InternalContext_data_frame_from_table_provider` <- function(self) {
  function(`provider_xptr`) {
    .savvy_wrap_InternalDataFrame(.Call(
      savvy_InternalContext_data_frame_from_table_provider__impl,
      `self`,
      `provider_xptr`
    ))
  }
}

`InternalContext_deregister_table` <- function(self) {
  function(`table_ref`) {
    invisible(.Call(savvy_InternalContext_deregister_table__impl, `self`, `table_ref`))
  }
}

`InternalContext_list_functions` <- function(self) {
  function() {
    .Call(savvy_InternalContext_list_functions__impl, `self`)
  }
}

`InternalContext_read_parquet` <- function(self) {
  function(`paths`) {
    .savvy_wrap_InternalDataFrame(.Call(
      savvy_InternalContext_read_parquet__impl,
      `self`,
      `paths`
    ))
  }
}

`InternalContext_register_scalar_udf` <- function(self) {
  function(`scalar_udf_xptr`) {
    invisible(.Call(
      savvy_InternalContext_register_scalar_udf__impl,
      `self`,
      `scalar_udf_xptr`
    ))
  }
}

`InternalContext_scalar_udf_xptr` <- function(self) {
  function(`name`) {
    .Call(savvy_InternalContext_scalar_udf_xptr__impl, `self`, `name`)
  }
}

`InternalContext_sql` <- function(self) {
  function(`query`) {
    .savvy_wrap_InternalDataFrame(.Call(savvy_InternalContext_sql__impl, `self`, `query`))
  }
}

`InternalContext_view` <- function(self) {
  function(`table_ref`) {
    .savvy_wrap_InternalDataFrame(.Call(
      savvy_InternalContext_view__impl,
      `self`,
      `table_ref`
    ))
  }
}

`.savvy_wrap_InternalContext` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`data_frame_from_array_stream` <- `InternalContext_data_frame_from_array_stream`(ptr)
  e$`data_frame_from_table_provider` <- `InternalContext_data_frame_from_table_provider`(
    ptr
  )
  e$`deregister_table` <- `InternalContext_deregister_table`(ptr)
  e$`list_functions` <- `InternalContext_list_functions`(ptr)
  e$`read_parquet` <- `InternalContext_read_parquet`(ptr)
  e$`register_scalar_udf` <- `InternalContext_register_scalar_udf`(ptr)
  e$`scalar_udf_xptr` <- `InternalContext_scalar_udf_xptr`(ptr)
  e$`sql` <- `InternalContext_sql`(ptr)
  e$`view` <- `InternalContext_view`(ptr)

  class(e) <- c("sedonadb::InternalContext", "InternalContext", "savvy_sedonadb__sealed")
  e
}


`InternalContext` <- new.env(parent = emptyenv())

### associated functions for InternalContext

`InternalContext`$`new` <- function(`option_keys`, `option_values`) {
  .savvy_wrap_InternalContext(.Call(
    savvy_InternalContext_new__impl,
    `option_keys`,
    `option_values`
  ))
}


class(`InternalContext`) <- c(
  "sedonadb::InternalContext__bundle",
  "savvy_sedonadb__sealed"
)

#' @export
`print.sedonadb::InternalContext__bundle` <- function(x, ...) {
  cat('sedonadb::InternalContext\n')
}

### wrapper functions for InternalDataFrame

`InternalDataFrame_aggregate` <- function(self) {
  function(`group_by_exprs_sexp`, `exprs_sexp`) {
    .savvy_wrap_InternalDataFrame(.Call(
      savvy_InternalDataFrame_aggregate__impl,
      `self`,
      `group_by_exprs_sexp`,
      `exprs_sexp`
    ))
  }
}

`InternalDataFrame_arrange` <- function(self) {
  function(`exprs_sexp`, `is_descending_sexp`) {
    .savvy_wrap_InternalDataFrame(.Call(
      savvy_InternalDataFrame_arrange__impl,
      `self`,
      `exprs_sexp`,
      `is_descending_sexp`
    ))
  }
}

`InternalDataFrame_collect` <- function(self) {
  function(`out`) {
    .Call(savvy_InternalDataFrame_collect__impl, `self`, `out`)
  }
}

`InternalDataFrame_compute` <- function(self) {
  function(`ctx`) {
    `ctx` <- .savvy_extract_ptr(`ctx`, "sedonadb::InternalContext")
    .savvy_wrap_InternalDataFrame(.Call(
      savvy_InternalDataFrame_compute__impl,
      `self`,
      `ctx`
    ))
  }
}

`InternalDataFrame_count` <- function(self) {
  function() {
    .Call(savvy_InternalDataFrame_count__impl, `self`)
  }
}

`InternalDataFrame_filter` <- function(self) {
  function(`exprs_sexp`) {
    .savvy_wrap_InternalDataFrame(.Call(
      savvy_InternalDataFrame_filter__impl,
      `self`,
      `exprs_sexp`
    ))
  }
}

`InternalDataFrame_join` <- function(self) {
  function(`right`, `on_sexp`, `join_type_str`, `left_alias`, `right_alias`) {
    `right` <- .savvy_extract_ptr(`right`, "sedonadb::InternalDataFrame")
    .savvy_wrap_InternalDataFrame(.Call(
      savvy_InternalDataFrame_join__impl,
      `self`,
      `right`,
      `on_sexp`,
      `join_type_str`,
      `left_alias`,
      `right_alias`
    ))
  }
}

`InternalDataFrame_limit` <- function(self) {
  function(`n`) {
    .savvy_wrap_InternalDataFrame(.Call(savvy_InternalDataFrame_limit__impl, `self`, `n`))
  }
}

`InternalDataFrame_primary_geometry_column_index` <- function(self) {
  function() {
    .Call(savvy_InternalDataFrame_primary_geometry_column_index__impl, `self`)
  }
}

`InternalDataFrame_select` <- function(self) {
  function(`exprs_sexp`) {
    .savvy_wrap_InternalDataFrame(.Call(
      savvy_InternalDataFrame_select__impl,
      `self`,
      `exprs_sexp`
    ))
  }
}

`InternalDataFrame_select_indices` <- function(self) {
  function(`names`, `indices`) {
    .savvy_wrap_InternalDataFrame(.Call(
      savvy_InternalDataFrame_select_indices__impl,
      `self`,
      `names`,
      `indices`
    ))
  }
}

`InternalDataFrame_show` <- function(self) {
  function(`ctx`, `width_chars`, `ascii`, `limit` = NULL) {
    `ctx` <- .savvy_extract_ptr(`ctx`, "sedonadb::InternalContext")
    .Call(
      savvy_InternalDataFrame_show__impl,
      `self`,
      `ctx`,
      `width_chars`,
      `ascii`,
      `limit`
    )
  }
}

`InternalDataFrame_to_arrow_schema` <- function(self) {
  function(`out`) {
    invisible(.Call(savvy_InternalDataFrame_to_arrow_schema__impl, `self`, `out`))
  }
}

`InternalDataFrame_to_arrow_stream` <- function(self) {
  function(`out`, `requested_schema_xptr`) {
    invisible(.Call(
      savvy_InternalDataFrame_to_arrow_stream__impl,
      `self`,
      `out`,
      `requested_schema_xptr`
    ))
  }
}

`InternalDataFrame_to_parquet` <- function(self) {
  function(
    `ctx`,
    `path`,
    `option_keys`,
    `option_values`,
    `partition_by`,
    `sort_by`,
    `single_file_output`
  ) {
    `ctx` <- .savvy_extract_ptr(`ctx`, "sedonadb::InternalContext")
    invisible(.Call(
      savvy_InternalDataFrame_to_parquet__impl,
      `self`,
      `ctx`,
      `path`,
      `option_keys`,
      `option_values`,
      `partition_by`,
      `sort_by`,
      `single_file_output`
    ))
  }
}

`InternalDataFrame_to_provider` <- function(self) {
  function() {
    .Call(savvy_InternalDataFrame_to_provider__impl, `self`)
  }
}

`InternalDataFrame_to_view` <- function(self) {
  function(`ctx`, `table_ref`, `overwrite`) {
    `ctx` <- .savvy_extract_ptr(`ctx`, "sedonadb::InternalContext")
    invisible(.Call(
      savvy_InternalDataFrame_to_view__impl,
      `self`,
      `ctx`,
      `table_ref`,
      `overwrite`
    ))
  }
}

`InternalDataFrame_with_params` <- function(self) {
  function(`params_sexp`) {
    .savvy_wrap_InternalDataFrame(.Call(
      savvy_InternalDataFrame_with_params__impl,
      `self`,
      `params_sexp`
    ))
  }
}

`.savvy_wrap_InternalDataFrame` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`aggregate` <- `InternalDataFrame_aggregate`(ptr)
  e$`arrange` <- `InternalDataFrame_arrange`(ptr)
  e$`collect` <- `InternalDataFrame_collect`(ptr)
  e$`compute` <- `InternalDataFrame_compute`(ptr)
  e$`count` <- `InternalDataFrame_count`(ptr)
  e$`filter` <- `InternalDataFrame_filter`(ptr)
  e$`join` <- `InternalDataFrame_join`(ptr)
  e$`limit` <- `InternalDataFrame_limit`(ptr)
  e$`primary_geometry_column_index` <- `InternalDataFrame_primary_geometry_column_index`(
    ptr
  )
  e$`select` <- `InternalDataFrame_select`(ptr)
  e$`select_indices` <- `InternalDataFrame_select_indices`(ptr)
  e$`show` <- `InternalDataFrame_show`(ptr)
  e$`to_arrow_schema` <- `InternalDataFrame_to_arrow_schema`(ptr)
  e$`to_arrow_stream` <- `InternalDataFrame_to_arrow_stream`(ptr)
  e$`to_parquet` <- `InternalDataFrame_to_parquet`(ptr)
  e$`to_provider` <- `InternalDataFrame_to_provider`(ptr)
  e$`to_view` <- `InternalDataFrame_to_view`(ptr)
  e$`with_params` <- `InternalDataFrame_with_params`(ptr)

  class(e) <- c(
    "sedonadb::InternalDataFrame",
    "InternalDataFrame",
    "savvy_sedonadb__sealed"
  )
  e
}


`InternalDataFrame` <- new.env(parent = emptyenv())

### associated functions for InternalDataFrame

class(`InternalDataFrame`) <- c(
  "sedonadb::InternalDataFrame__bundle",
  "savvy_sedonadb__sealed"
)

#' @export
`print.sedonadb::InternalDataFrame__bundle` <- function(x, ...) {
  cat('sedonadb::InternalDataFrame\n')
}

### wrapper functions for SedonaDBExpr

`SedonaDBExpr_alias` <- function(self) {
  function(`name`) {
    .savvy_wrap_SedonaDBExpr(.Call(savvy_SedonaDBExpr_alias__impl, `self`, `name`))
  }
}

`SedonaDBExpr_cast` <- function(self) {
  function(`schema_xptr`) {
    .savvy_wrap_SedonaDBExpr(.Call(savvy_SedonaDBExpr_cast__impl, `self`, `schema_xptr`))
  }
}

`SedonaDBExpr_debug_string` <- function(self) {
  function() {
    .Call(savvy_SedonaDBExpr_debug_string__impl, `self`)
  }
}

`SedonaDBExpr_display` <- function(self) {
  function() {
    .Call(savvy_SedonaDBExpr_display__impl, `self`)
  }
}

`SedonaDBExpr_negate` <- function(self) {
  function() {
    .savvy_wrap_SedonaDBExpr(.Call(savvy_SedonaDBExpr_negate__impl, `self`))
  }
}

`SedonaDBExpr_parse_binary` <- function(self) {
  function() {
    .Call(savvy_SedonaDBExpr_parse_binary__impl, `self`)
  }
}

`SedonaDBExpr_qualified_name` <- function(self) {
  function() {
    .Call(savvy_SedonaDBExpr_qualified_name__impl, `self`)
  }
}

`SedonaDBExpr_variant_name` <- function(self) {
  function() {
    .Call(savvy_SedonaDBExpr_variant_name__impl, `self`)
  }
}

`.savvy_wrap_SedonaDBExpr` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`alias` <- `SedonaDBExpr_alias`(ptr)
  e$`cast` <- `SedonaDBExpr_cast`(ptr)
  e$`debug_string` <- `SedonaDBExpr_debug_string`(ptr)
  e$`display` <- `SedonaDBExpr_display`(ptr)
  e$`negate` <- `SedonaDBExpr_negate`(ptr)
  e$`parse_binary` <- `SedonaDBExpr_parse_binary`(ptr)
  e$`qualified_name` <- `SedonaDBExpr_qualified_name`(ptr)
  e$`variant_name` <- `SedonaDBExpr_variant_name`(ptr)

  class(e) <- c("sedonadb::SedonaDBExpr", "SedonaDBExpr", "savvy_sedonadb__sealed")
  e
}


`SedonaDBExpr` <- new.env(parent = emptyenv())

### associated functions for SedonaDBExpr

class(`SedonaDBExpr`) <- c("sedonadb::SedonaDBExpr__bundle", "savvy_sedonadb__sealed")

#' @export
`print.sedonadb::SedonaDBExpr__bundle` <- function(x, ...) {
  cat('sedonadb::SedonaDBExpr\n')
}

### wrapper functions for SedonaDBExprFactory

`SedonaDBExprFactory_aggregate_function` <- function(self) {
  function(`name`, `args`, `na_rm` = NULL, `distinct` = NULL) {
    .savvy_wrap_SedonaDBExpr(.Call(
      savvy_SedonaDBExprFactory_aggregate_function__impl,
      `self`,
      `name`,
      `args`,
      `na_rm`,
      `distinct`
    ))
  }
}

`SedonaDBExprFactory_any_function` <- function(self) {
  function(`name`, `args`, `na_rm` = NULL) {
    .savvy_wrap_SedonaDBExpr(.Call(
      savvy_SedonaDBExprFactory_any_function__impl,
      `self`,
      `name`,
      `args`,
      `na_rm`
    ))
  }
}

`SedonaDBExprFactory_binary` <- function(self) {
  function(`op`, `lhs`, `rhs`) {
    `lhs` <- .savvy_extract_ptr(`lhs`, "sedonadb::SedonaDBExpr")
    `rhs` <- .savvy_extract_ptr(`rhs`, "sedonadb::SedonaDBExpr")
    .savvy_wrap_SedonaDBExpr(.Call(
      savvy_SedonaDBExprFactory_binary__impl,
      `self`,
      `op`,
      `lhs`,
      `rhs`
    ))
  }
}

`SedonaDBExprFactory_column` <- function(self) {
  function(`name`, `qualifier` = NULL) {
    .savvy_wrap_SedonaDBExpr(.Call(
      savvy_SedonaDBExprFactory_column__impl,
      `self`,
      `name`,
      `qualifier`
    ))
  }
}

`SedonaDBExprFactory_scalar_function` <- function(self) {
  function(`name`, `args`) {
    .savvy_wrap_SedonaDBExpr(.Call(
      savvy_SedonaDBExprFactory_scalar_function__impl,
      `self`,
      `name`,
      `args`
    ))
  }
}

`.savvy_wrap_SedonaDBExprFactory` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`aggregate_function` <- `SedonaDBExprFactory_aggregate_function`(ptr)
  e$`any_function` <- `SedonaDBExprFactory_any_function`(ptr)
  e$`binary` <- `SedonaDBExprFactory_binary`(ptr)
  e$`column` <- `SedonaDBExprFactory_column`(ptr)
  e$`scalar_function` <- `SedonaDBExprFactory_scalar_function`(ptr)

  class(e) <- c(
    "sedonadb::SedonaDBExprFactory",
    "SedonaDBExprFactory",
    "savvy_sedonadb__sealed"
  )
  e
}


`SedonaDBExprFactory` <- new.env(parent = emptyenv())

### associated functions for SedonaDBExprFactory

`SedonaDBExprFactory`$`literal` <- function(`array_xptr`, `schema_xptr`) {
  .savvy_wrap_SedonaDBExpr(.Call(
    savvy_SedonaDBExprFactory_literal__impl,
    `array_xptr`,
    `schema_xptr`
  ))
}

`SedonaDBExprFactory`$`new` <- function(`ctx`) {
  `ctx` <- .savvy_extract_ptr(`ctx`, "sedonadb::InternalContext")
  .savvy_wrap_SedonaDBExprFactory(.Call(savvy_SedonaDBExprFactory_new__impl, `ctx`))
}


class(`SedonaDBExprFactory`) <- c(
  "sedonadb::SedonaDBExprFactory__bundle",
  "savvy_sedonadb__sealed"
)

#' @export
`print.sedonadb::SedonaDBExprFactory__bundle` <- function(x, ...) {
  cat('sedonadb::SedonaDBExprFactory\n')
}
